org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
android.useAndroidX=true
kotlin.incremental=true
# Built-in Kotlin: Flutter manages Kotlin version automatically
android.builtInKotlin=true
flutter.kotlinVersion=2.2.20
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false

# Tối ưu R8 full mode
android.enableR8.fullMode=true
android.enableR8.lint.violations=false

# Tối ưu build cache
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true

# Tối ưu resource shrinking
android.experimental.enableNewResourceShrinker=true
